movement = csvread('movement.csv',6,0);
samples = [0:1233];
accel_x = movement(:,1);
accel_y = movement(:,2);
accel_z = movement(:,3);
gyro_x = movement(:,4);
gyro_y = movement(:,5);
gyro_z = movement(:,6);
lim = 1250 %change this value
figure(1);
subplot(2,1,1);
plot(samples, gyro_x, '-');
hold on;
plot(samples, gyro_y, '-');
plot(samples, gyro_z, '-');
legend('X-axis','Y-axis','Z-axis');
title("Gyroscope");
xlabel("Sample");
hold off;
axis tight;
%xlim([0 lim]);

subplot(2,1,2);
plot(samples, accel_x, '-');
hold on;
plot(samples, accel_y, '-');
plot(samples, accel_z, '-');
legend('X-axis','Y-axis','Z-axis');
title("Accelerometer");
xlabel("Sample");
hold off;
axis tight;
%xlim([0 lim]);
